export enum Keywords {
    Pantalla = 'Pantalla',
    Required = 'Requerido',
    Mostramos = 'Mostramos',
    Opciones = 'Opciones',
    Lista = 'Lista',
    SiEliges = 'Si eliges',
    IrAPantalla = 'Ir a pantalla',
    Salir = 'Salir',
    Cancelar = 'Cancelar',
    Sí = 'Sí',
    No = 'No',
    Imagen = 'Imagen',
    Formulario = '[FORMULARIO]',
    Habilitado = 'habilitado',
}